#!/usr/bin/env bash
# Grid Platform — install control plane on a Linux VM (Ubuntu 22.04/24.04).
#
# Usage (as root or with sudo):
#   curl -fsSL https://raw.githubusercontent.com/gridplatform/grid-core/main/install/install.sh | sudo bash
#   # or, from a clone:
#   sudo bash install/install.sh
#
# Env overrides:
#   GRID_HOME=/opt/grid
#   GRID_REF=main                 # git ref for core/ui/cli
#   GRID_AUTH_ADMIN_EMAIL=...
#   GRID_AUTH_ADMIN_PASSWORD=...  # required for non-interactive; else prompted
#   GRID_MODULE_BANK_REF=v0.1.0
#   GRID_GITOPS_REPO_URL=...
#   GRID_TF_BACKEND=s3|gcs|azurerm (+ bucket/lock) — required (install/check-env.sh)
#   GRID_USE_NATIVE=1             # systemd + nginx instead of Compose (default is Compose)
#   GRID_USE_COMPOSE=0            # same as GRID_USE_NATIVE=1 (legacy alias invert)
#   GRID_SKIP_SYSTEMD=1           # native path: clone+build only

set -euo pipefail

GRID_HOME="${GRID_HOME:-/opt/grid}"
GRID_REF="${GRID_REF:-main}"
GRID_ORG="${GRID_ORG:-https://github.com/gridplatform}"
GRID_HTTP_PORT="${GRID_HTTP_PORT:-80}"
NODE_MAJOR="${NODE_MAJOR:-24}"
TERRAFORM_VERSION="${TERRAFORM_VERSION:-1.9.8}"

log()  { printf '\n==> %s\n' "$*"; }
die()  { printf 'ERROR: %s\n' "$*" >&2; exit 1; }
need_root() { [[ ${EUID:-$(id -u)} -eq 0 ]] || die "run as root (sudo)"; }

clone_or_update() {
  local url="$1" dest="$2" ref="$3"
  if [[ -d "$dest/.git" ]]; then
    git -C "$dest" fetch --depth 1 origin "$ref"
    git -C "$dest" checkout -q FETCH_HEAD
  else
    git clone --depth 1 --branch "$ref" "$url" "$dest" \
      || git clone --depth 1 "$url" "$dest" && git -C "$dest" checkout -q "$ref"
  fi
}

install_node() {
  if command -v node >/dev/null 2>&1; then
    local major
    major="$(node -v | sed -E 's/^v([0-9]+).*/\1/')"
    if [[ "$major" -ge "$NODE_MAJOR" ]]; then
      log "Node $(node -v) OK"
      return
    fi
  fi
  log "Installing Node.js ${NODE_MAJOR}.x"
  apt-get install -y ca-certificates curl gnupg
  mkdir -p /etc/apt/keyrings
  curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key \
    | gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg
  echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_${NODE_MAJOR}.x nodistro main" \
    > /etc/apt/sources.list.d/nodesource.list
  apt-get update
  apt-get install -y nodejs
  node -v
  npm -v
}

install_terraform() {
  if command -v terraform >/dev/null 2>&1; then
    log "Terraform $(terraform version -json 2>/dev/null | sed -n 's/.*"terraform_version":"\([^"]*\)".*/\1/p' || terraform version | head -1) OK"
    return
  fi
  log "Installing Terraform ${TERRAFORM_VERSION}"
  local arch tf_arch
  arch="$(dpkg --print-architecture)"
  case "$arch" in
    amd64) tf_arch=amd64 ;;
    arm64) tf_arch=arm64 ;;
    *) die "unsupported arch: $arch" ;;
  esac
  curl -fsSL "https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_${tf_arch}.zip" \
    -o /tmp/terraform.zip
  apt-get install -y unzip
  unzip -o /tmp/terraform.zip -d /usr/local/bin
  rm -f /tmp/terraform.zip
  terraform version
}

prompt_password() {
  if [[ -n "${GRID_AUTH_ADMIN_PASSWORD:-}" ]]; then
    return
  fi
  if [[ -t 0 ]]; then
    read -r -s -p "Admin password for Grid console: " GRID_AUTH_ADMIN_PASSWORD
    echo
    [[ -n "$GRID_AUTH_ADMIN_PASSWORD" ]] || die "password required"
    export GRID_AUTH_ADMIN_PASSWORD
  else
    die "set GRID_AUTH_ADMIN_PASSWORD for non-interactive install"
  fi
}

write_env() {
  local env_file="$1"
  mkdir -p "$(dirname "$env_file")"
  cat >"$env_file" <<EOF
# Generated by grid install.sh — $(date -u +%Y-%m-%dT%H:%MZ)
GRID_AUTH_ADMIN_EMAIL=${GRID_AUTH_ADMIN_EMAIL:-admin@grid.local}
GRID_AUTH_ADMIN_PASSWORD=${GRID_AUTH_ADMIN_PASSWORD}
GRID_HTTP_PORT=${GRID_HTTP_PORT}
GRID_GITOPS_REPO_URL=${GRID_GITOPS_REPO_URL:-https://github.com/gridplatform/grid-config.git}
GRID_GITOPS_BRANCH=${GRID_GITOPS_BRANCH:-main}
GRID_MODULE_BANK=${GRID_MODULE_BANK:-https://github.com/gridplatform/grid-terraform.git}
GRID_MODULE_BANK_REF=${GRID_MODULE_BANK_REF:-v0.1.0}
GRID_CLI_REF=${GRID_REF}
PORT=3000
GRID_APP_ENV=production
GRID_CLI_ROOT=${GRID_HOME}/grid-cli
GRID_DATA_DIR=/var/lib/grid/data
GRID_WORK_DIR=/var/lib/grid/workspaces
GRID_CONFIG_ROOT=/var/lib/grid/desired-state
GRID_TERRAFORM_BIN=terraform
# Remote state — required (see grid-docs install/remote-state)
GRID_TF_BACKEND=${GRID_TF_BACKEND:-}
GRID_TF_STATE_BUCKET=${GRID_TF_STATE_BUCKET:-}
GRID_TF_LOCK_TABLE=${GRID_TF_LOCK_TABLE:-}
GRID_TF_STATE_REGION=${GRID_TF_STATE_REGION:-}
GRID_TF_AZURE_RESOURCE_GROUP=${GRID_TF_AZURE_RESOURCE_GROUP:-}
GRID_TF_AZURE_STORAGE_ACCOUNT=${GRID_TF_AZURE_STORAGE_ACCOUNT:-}
GRID_TF_AZURE_CONTAINER=${GRID_TF_AZURE_CONTAINER:-}
EOF
  chmod 600 "$env_file"
}

install_compose_path() {
  need_root
  prompt_password
  log "Installing Docker (if needed) + Compose path (detached, survives logout + reboot)"
  apt-get update
  apt-get install -y ca-certificates curl git
  if ! command -v docker >/dev/null 2>&1; then
    curl -fsSL https://get.docker.com | sh
  fi
  # Docker must start on boot so containers with restart: unless-stopped come back
  systemctl enable --now docker

  mkdir -p "$GRID_HOME"
  clone_or_update "${GRID_ORG}/grid-core.git" "${GRID_HOME}/grid-core" "$GRID_REF"
  write_env "${GRID_HOME}/grid-core/install/.env"
  cd "${GRID_HOME}/grid-core"
  # Production-only: check-env + compose (no skip / no dev profile)
  bash install/compose-up.sh

  # Ensure stack is brought up again after reboot (in addition to container restart policies)
  cp "${GRID_HOME}/grid-core/install/systemd/grid-compose.service" /etc/systemd/system/grid-compose.service
  # Point WorkingDirectory at this install (unit file uses /opt/grid/grid-core by default)
  if [[ "$GRID_HOME" != "/opt/grid" ]]; then
    sed -i "s|/opt/grid/grid-core|${GRID_HOME}/grid-core|g" /etc/systemd/system/grid-compose.service
  fi
  systemctl daemon-reload
  systemctl enable --now grid-compose.service

  log "Grid is running in the background (Docker Compose)."
  log "  Survives SSH logout; restarts on reboot (docker + grid-compose + restart: unless-stopped)."
  log "  Open http://<this-host>:${GRID_HTTP_PORT}/  (admin: ${GRID_AUTH_ADMIN_EMAIL:-admin@grid.local})"
  log "  Status:  docker compose -f ${GRID_HOME}/grid-core/install/docker-compose.yml ps"
  log "  Logs:    docker compose -f ${GRID_HOME}/grid-core/install/docker-compose.yml logs -f --tail=100"
  log "  Stop:    systemctl stop grid-compose   # or: docker compose ... stop"
}

install_systemd_path() {
  need_root
  prompt_password

  log "Apt packages"
  export DEBIAN_FRONTEND=noninteractive
  apt-get update
  apt-get install -y curl git ca-certificates build-essential unzip

  install_node
  install_terraform

  log "System user + dirs"
  id -u grid >/dev/null 2>&1 || useradd --system --home "$GRID_HOME" --shell /usr/sbin/nologin grid
  mkdir -p "$GRID_HOME" /var/lib/grid/{data,workspaces,desired-state} /etc/grid
  chown -R grid:grid /var/lib/grid

  log "Clone repositories @ ${GRID_REF}"
  clone_or_update "${GRID_ORG}/grid-core.git" "${GRID_HOME}/grid-core" "$GRID_REF"
  clone_or_update "${GRID_ORG}/grid-cli.git"  "${GRID_HOME}/grid-cli"  "$GRID_REF"
  clone_or_update "${GRID_ORG}/grid-ui.git"   "${GRID_HOME}/grid-ui"   "$GRID_REF"
  chown -R grid:grid "$GRID_HOME"

  write_env /etc/grid/grid.env
  GRID_ENV_FILE=/etc/grid/grid.env bash "${GRID_HOME}/grid-core/install/check-env.sh"
  # shellcheck disable=SC1091
  set -a; source /etc/grid/grid.env; set +a

  log "Build grid-cli"
  cd "${GRID_HOME}/grid-cli"
  sudo -u grid npm ci
  sudo -u grid npm run build

  log "Build grid-core"
  cd "${GRID_HOME}/grid-core"
  sudo -u grid npm ci
  sudo -u grid npm run build

  log "Build grid-ui"
  cd "${GRID_HOME}/grid-ui"
  sudo -u grid npm ci
  # Relative /api/v1 — host nginx proxies to core (see install/nginx-host.conf)
  sudo -u grid VITE_GRID_API_URL=/api/v1 npm run build

  chown -R grid:grid "$GRID_HOME" /var/lib/grid

  if [[ "${GRID_SKIP_SYSTEMD:-0}" == "1" ]]; then
    log "GRID_SKIP_SYSTEMD=1 — skipping unit install"
    return
  fi

  log "Install systemd unit (API) + nginx (UI + /api proxy)"
  cp "${GRID_HOME}/grid-core/install/systemd/grid-core.service" /etc/systemd/system/
  systemctl daemon-reload
  systemctl enable --now grid-core.service

  apt-get install -y nginx
  cp "${GRID_HOME}/grid-core/install/nginx-host.conf" /etc/nginx/sites-available/grid
  ln -sfn /etc/nginx/sites-available/grid /etc/nginx/sites-enabled/grid
  rm -f /etc/nginx/sites-enabled/default
  nginx -t
  systemctl enable --now nginx
  systemctl reload nginx

  log "Done — Grid is managed by systemd (survives logout + reboot)."
  log "  Open http://<this-host>/  (admin: ${GRID_AUTH_ADMIN_EMAIL:-admin@grid.local})"
  log "  API health: http://<this-host>/health"
  log "  Status: systemctl status grid-core nginx"
  log "  Logs:   journalctl -u grid-core -f"
  log "Docs: https://github.com/gridplatform/grid-docs/blob/main/docs/install/vm.md"
}

main() {
  # Default: Compose on the VM. Native systemd path: GRID_USE_NATIVE=1
  local use_native="${GRID_USE_NATIVE:-0}"
  if [[ "${GRID_USE_COMPOSE:-1}" == "0" ]]; then
    use_native=1
  fi
  if [[ "$use_native" == "1" ]]; then
    install_systemd_path
  else
    install_compose_path
  fi
}

main "$@"
